-- ============================================================================
-- Rufesto PRODUCTION baseline — PART 2 (run AFTER _prod_baseline.sql)
-- Target: prod Supabase project bjohnoaezfmrgunvjixt (rufesto.com / r_rufesto)
-- ============================================================================

-- ============================ 5. CONSTRAINTS ===============================
-- 5a. Primary keys
ALTER TABLE public.ad_campaigns ADD CONSTRAINT ad_campaigns_pkey PRIMARY KEY (id);
ALTER TABLE public.attendance ADD CONSTRAINT attendance_pkey PRIMARY KEY (id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);
ALTER TABLE public.customer_profiles ADD CONSTRAINT customer_profiles_pkey PRIMARY KEY (user_id);
ALTER TABLE public.deliveries ADD CONSTRAINT deliveries_pkey PRIMARY KEY (id);
ALTER TABLE public.delivery_items ADD CONSTRAINT delivery_items_pkey PRIMARY KEY (id);
ALTER TABLE public.departments ADD CONSTRAINT departments_pkey PRIMARY KEY (id);
ALTER TABLE public.dish_allergens ADD CONSTRAINT dish_allergens_pkey PRIMARY KEY (dish_id, allergen);
ALTER TABLE public.dish_ingredients ADD CONSTRAINT dish_ingredients_pkey PRIMARY KEY (id);
ALTER TABLE public.dish_photos ADD CONSTRAINT dish_photos_pkey PRIMARY KEY (id);
ALTER TABLE public.dish_price_history ADD CONSTRAINT dish_price_history_pkey PRIMARY KEY (id);
ALTER TABLE public.dishes ADD CONSTRAINT dishes_pkey PRIMARY KEY (id);
ALTER TABLE public.employees ADD CONSTRAINT employees_pkey PRIMARY KEY (id);
ALTER TABLE public.expenses ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);
ALTER TABLE public.feedback ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);
ALTER TABLE public.ingredient_batches ADD CONSTRAINT ingredient_batches_pkey PRIMARY KEY (id);
ALTER TABLE public.ingredients ADD CONSTRAINT ingredients_pkey PRIMARY KEY (id);
ALTER TABLE public.invoices ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);
ALTER TABLE public.kds_tickets ADD CONSTRAINT kds_tickets_pkey PRIMARY KEY (id);
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.likes ADD CONSTRAINT likes_pkey PRIMARY KEY (id);
ALTER TABLE public.loyalty_accounts ADD CONSTRAINT loyalty_accounts_pkey PRIMARY KEY (user_id);
ALTER TABLE public.loyalty_transactions ADD CONSTRAINT loyalty_transactions_pkey PRIMARY KEY (id);
ALTER TABLE public.menu_sections ADD CONSTRAINT menu_sections_pkey PRIMARY KEY (id);
ALTER TABLE public.menus ADD CONSTRAINT menus_pkey PRIMARY KEY (id);
ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.operating_hours ADD CONSTRAINT operating_hours_pkey PRIMARY KEY (id);
ALTER TABLE public.order_items ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);
ALTER TABLE public.orders ADD CONSTRAINT orders_pkey PRIMARY KEY (id);
ALTER TABLE public.otp_log ADD CONSTRAINT otp_log_pkey PRIMARY KEY (id);
ALTER TABLE public.payment_splits ADD CONSTRAINT payment_splits_pkey PRIMARY KEY (id);
ALTER TABLE public.payments ADD CONSTRAINT payments_pkey PRIMARY KEY (id);
ALTER TABLE public.payroll_items ADD CONSTRAINT payroll_items_pkey PRIMARY KEY (id);
ALTER TABLE public.payroll_runs ADD CONSTRAINT payroll_runs_pkey PRIMARY KEY (id);
ALTER TABLE public.performance_reviews ADD CONSTRAINT performance_reviews_pkey PRIMARY KEY (id);
ALTER TABLE public.po_items ADD CONSTRAINT po_items_pkey PRIMARY KEY (id);
ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_pkey PRIMARY KEY (id);
ALTER TABLE public.recipe_versions ADD CONSTRAINT recipe_versions_pkey PRIMARY KEY (id);
ALTER TABLE public.refunds ADD CONSTRAINT refunds_pkey PRIMARY KEY (id);
ALTER TABLE public.restaurant_settings ADD CONSTRAINT restaurant_settings_pkey PRIMARY KEY (restaurant_id);
ALTER TABLE public.restaurant_subscriptions ADD CONSTRAINT restaurant_subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE public.restaurant_suppliers ADD CONSTRAINT restaurant_suppliers_pkey PRIMARY KEY (id);
ALTER TABLE public.restaurants ADD CONSTRAINT restaurants_pkey PRIMARY KEY (id);
ALTER TABLE public.review_comments ADD CONSTRAINT review_comments_pkey PRIMARY KEY (id);
ALTER TABLE public.reviews ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);
ALTER TABLE public.salary_history ADD CONSTRAINT salary_history_pkey PRIMARY KEY (id);
ALTER TABLE public.saved_dishes ADD CONSTRAINT saved_dishes_pkey PRIMARY KEY (id);
ALTER TABLE public.schema_migrations ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);
ALTER TABLE public.sections ADD CONSTRAINT sections_pkey PRIMARY KEY (id);
ALTER TABLE public.shifts ADD CONSTRAINT shifts_pkey PRIMARY KEY (id);
ALTER TABLE public.special_closures ADD CONSTRAINT special_closures_pkey PRIMARY KEY (id);
ALTER TABLE public.staff ADD CONSTRAINT staff_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_alerts ADD CONSTRAINT stock_alerts_pkey PRIMARY KEY (id);
ALTER TABLE public.stock_log ADD CONSTRAINT stock_log_pkey PRIMARY KEY (id);
ALTER TABLE public.subscription_plans ADD CONSTRAINT subscription_plans_pkey PRIMARY KEY (id);
ALTER TABLE public.supplier_catalog ADD CONSTRAINT supplier_catalog_pkey PRIMARY KEY (id);
ALTER TABLE public.supplier_price_history ADD CONSTRAINT supplier_price_history_pkey PRIMARY KEY (id);
ALTER TABLE public.supplier_reviews ADD CONSTRAINT supplier_reviews_pkey PRIMARY KEY (id);
ALTER TABLE public.suppliers ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);
ALTER TABLE public.table_state_log ADD CONSTRAINT table_state_log_pkey PRIMARY KEY (id);
ALTER TABLE public.tables ADD CONSTRAINT tables_pkey PRIMARY KEY (id);
ALTER TABLE public.tip_distribution ADD CONSTRAINT tip_distribution_pkey PRIMARY KEY (id);
ALTER TABLE public.user_follows ADD CONSTRAINT user_follows_pkey PRIMARY KEY (id);
ALTER TABLE public.user_sessions ADD CONSTRAINT user_sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE public.waitlist ADD CONSTRAINT waitlist_pkey PRIMARY KEY (id);
ALTER TABLE public.waste_log ADD CONSTRAINT waste_log_pkey PRIMARY KEY (id);

-- 5b. Unique
ALTER TABLE public.attendance ADD CONSTRAINT attendance_shift_id_key UNIQUE (shift_id);
ALTER TABLE public.departments ADD CONSTRAINT departments_restaurant_id_name_key UNIQUE (restaurant_id, name);
ALTER TABLE public.dish_ingredients ADD CONSTRAINT dish_ingredients_dish_id_ingredient_id_key UNIQUE (dish_id, ingredient_id);
ALTER TABLE public.employees ADD CONSTRAINT employees_restaurant_id_user_id_key UNIQUE (restaurant_id, user_id);
ALTER TABLE public.ingredients ADD CONSTRAINT ingredients_restaurant_id_name_key UNIQUE (restaurant_id, name);
ALTER TABLE public.invoices ADD CONSTRAINT invoices_invoice_number_key UNIQUE (invoice_number);
ALTER TABLE public.kds_tickets ADD CONSTRAINT kds_tickets_order_item_id_key UNIQUE (order_item_id);
ALTER TABLE public.likes ADD CONSTRAINT likes_user_id_target_type_target_id_key UNIQUE (user_id, target_type, target_id);
ALTER TABLE public.menu_sections ADD CONSTRAINT menu_sections_menu_id_name_key UNIQUE (menu_id, name);
ALTER TABLE public.menus ADD CONSTRAINT menus_restaurant_id_name_key UNIQUE (restaurant_id, name);
ALTER TABLE public.operating_hours ADD CONSTRAINT operating_hours_restaurant_id_day_of_week_key UNIQUE (restaurant_id, day_of_week);
ALTER TABLE public.payroll_items ADD CONSTRAINT payroll_items_payroll_run_id_employee_id_key UNIQUE (payroll_run_id, employee_id);
ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_po_number_key UNIQUE (po_number);
ALTER TABLE public.recipe_versions ADD CONSTRAINT recipe_versions_dish_id_version_number_key UNIQUE (dish_id, version_number);
ALTER TABLE public.restaurant_suppliers ADD CONSTRAINT restaurant_suppliers_restaurant_id_supplier_id_key UNIQUE (restaurant_id, supplier_id);
ALTER TABLE public.restaurants ADD CONSTRAINT restaurants_slug_key UNIQUE (slug);
ALTER TABLE public.reviews ADD CONSTRAINT reviews_dish_id_user_id_key UNIQUE (dish_id, user_id);
ALTER TABLE public.saved_dishes ADD CONSTRAINT saved_dishes_user_id_dish_id_key UNIQUE (user_id, dish_id);
ALTER TABLE public.sections ADD CONSTRAINT sections_restaurant_id_name_key UNIQUE (restaurant_id, name);
ALTER TABLE public.special_closures ADD CONSTRAINT special_closures_restaurant_id_closed_date_key UNIQUE (restaurant_id, closed_date);
ALTER TABLE public.staff ADD CONSTRAINT staff_restaurant_id_user_id_key UNIQUE (restaurant_id, user_id);
ALTER TABLE public.subscription_plans ADD CONSTRAINT subscription_plans_name_key UNIQUE (name);
ALTER TABLE public.supplier_catalog ADD CONSTRAINT supplier_catalog_supplier_id_item_code_key UNIQUE (supplier_id, item_code);
ALTER TABLE public.suppliers ADD CONSTRAINT suppliers_slug_key UNIQUE (slug);
ALTER TABLE public.tables ADD CONSTRAINT tables_qr_code_token_key UNIQUE (qr_code_token);
ALTER TABLE public.tables ADD CONSTRAINT tables_restaurant_id_table_number_key UNIQUE (restaurant_id, table_number);
ALTER TABLE public.user_follows ADD CONSTRAINT user_follows_user_id_restaurant_id_key UNIQUE (user_id, restaurant_id);
ALTER TABLE public.users ADD CONSTRAINT users_email_key UNIQUE (email);
ALTER TABLE public.users ADD CONSTRAINT users_phone_key UNIQUE (phone);

-- 5c. Check
ALTER TABLE public.ad_campaigns ADD CONSTRAINT ad_campaigns_budget_check CHECK ((budget > (0)::numeric));
ALTER TABLE public.ad_campaigns ADD CONSTRAINT ad_campaigns_check CHECK ((ends_at > starts_at));
ALTER TABLE public.ad_campaigns ADD CONSTRAINT ad_campaigns_check1 CHECK ((spent <= budget));
ALTER TABLE public.ad_campaigns ADD CONSTRAINT ad_campaigns_daily_limit_check CHECK ((daily_limit > (0)::numeric));
ALTER TABLE public.ad_campaigns ADD CONSTRAINT ad_campaigns_spent_check CHECK ((spent >= (0)::numeric));
ALTER TABLE public.ad_campaigns ADD CONSTRAINT ad_campaigns_status_check CHECK ((status = ANY (ARRAY['draft'::text,'active'::text,'paused'::text,'completed'::text,'cancelled'::text])));
ALTER TABLE public.ad_campaigns ADD CONSTRAINT ad_campaigns_type_check CHECK ((type = ANY (ARRAY['feed_placement'::text,'discount'::text,'highlight'::text,'banner'::text])));
ALTER TABLE public.attendance ADD CONSTRAINT attendance_status_check CHECK ((status = ANY (ARRAY['pending'::text,'present'::text,'absent'::text,'late'::text,'half_day'::text])));
ALTER TABLE public.bookings ADD CONSTRAINT bookings_check CHECK ((reserved_until > reserved_from));
ALTER TABLE public.bookings ADD CONSTRAINT bookings_party_size_check CHECK ((party_size > 0));
ALTER TABLE public.bookings ADD CONSTRAINT bookings_source_check CHECK ((source = ANY (ARRAY['app'::text,'qr_scan'::text,'phone'::text,'walk_in'::text])));
ALTER TABLE public.customer_profiles ADD CONSTRAINT customer_profiles_no_show_count_check CHECK ((no_show_count >= 0));
ALTER TABLE public.customer_profiles ADD CONSTRAINT customer_profiles_total_spent_check CHECK ((total_spent >= (0)::numeric));
ALTER TABLE public.customer_profiles ADD CONSTRAINT customer_profiles_total_visits_check CHECK ((total_visits >= 0));
ALTER TABLE public.customer_profiles ADD CONSTRAINT customer_profiles_unpaid_count_check CHECK ((unpaid_count >= 0));
ALTER TABLE public.deliveries ADD CONSTRAINT deliveries_status_check CHECK ((status = ANY (ARRAY['pending'::text,'accepted'::text,'partial'::text,'disputed'::text])));
ALTER TABLE public.delivery_items ADD CONSTRAINT delivery_items_condition_check CHECK ((condition = ANY (ARRAY['good'::text,'damaged'::text,'rejected'::text])));
ALTER TABLE public.delivery_items ADD CONSTRAINT delivery_items_received_qty_check CHECK ((received_qty > (0)::numeric));
ALTER TABLE public.dish_ingredients ADD CONSTRAINT dish_ingredients_quantity_check CHECK ((quantity > (0)::numeric));
ALTER TABLE public.dishes ADD CONSTRAINT dishes_calories_check CHECK ((calories >= 0));
ALTER TABLE public.dishes ADD CONSTRAINT dishes_prep_time_min_check CHECK ((prep_time_min > 0));
ALTER TABLE public.dishes ADD CONSTRAINT dishes_price_check CHECK ((price >= (0)::numeric));
ALTER TABLE public.dishes ADD CONSTRAINT dishes_spice_level_check CHECK (((spice_level >= 1) AND (spice_level <= 3)));
ALTER TABLE public.employees ADD CONSTRAINT employees_base_salary_check CHECK ((base_salary >= (0)::numeric));
ALTER TABLE public.employees ADD CONSTRAINT employees_employment_type_check CHECK ((employment_type = ANY (ARRAY['full_time'::text,'part_time'::text,'contractor'::text,'intern'::text])));
ALTER TABLE public.employees ADD CONSTRAINT employees_pay_frequency_check CHECK ((pay_frequency = ANY (ARRAY['hourly'::text,'daily'::text,'weekly'::text,'bi_weekly'::text,'monthly'::text])));
ALTER TABLE public.expenses ADD CONSTRAINT expenses_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE public.expenses ADD CONSTRAINT expenses_category_check CHECK ((category = ANY (ARRAY['food_cost'::text,'labor'::text,'utilities'::text,'rent'::text,'equipment'::text,'marketing'::text,'maintenance'::text,'platform_fee'::text,'other'::text])));
ALTER TABLE public.feedback ADD CONSTRAINT feedback_rating_check CHECK (((rating >= 1) AND (rating <= 5)));
ALTER TABLE public.ingredient_batches ADD CONSTRAINT ingredient_batches_check CHECK ((remaining_qty <= quantity));
ALTER TABLE public.ingredient_batches ADD CONSTRAINT ingredient_batches_quantity_check CHECK ((quantity > (0)::numeric));
ALTER TABLE public.ingredient_batches ADD CONSTRAINT ingredient_batches_remaining_qty_check CHECK ((remaining_qty >= (0)::numeric));
ALTER TABLE public.ingredients ADD CONSTRAINT chk_stock_non_negative CHECK ((stock_qty >= (0)::numeric));
ALTER TABLE public.ingredients ADD CONSTRAINT ingredients_category_check CHECK ((category = ANY (ARRAY['meat'::text,'seafood'::text,'dairy'::text,'produce'::text,'grain'::text,'spice'::text,'sauce'::text,'beverage'::text,'alcohol'::text,'other'::text])));
ALTER TABLE public.ingredients ADD CONSTRAINT ingredients_low_threshold_check CHECK ((low_threshold >= (0)::numeric));
ALTER TABLE public.ingredients ADD CONSTRAINT ingredients_unit_check CHECK ((unit = ANY (ARRAY['g'::text,'kg'::text,'ml'::text,'l'::text,'pcs'::text,'portion'::text])));
ALTER TABLE public.invoices ADD CONSTRAINT invoices_invoice_type_check CHECK ((invoice_type = ANY (ARRAY['customer'::text,'supplier'::text,'platform_fee'::text])));
ALTER TABLE public.invoices ADD CONSTRAINT invoices_status_check CHECK ((status = ANY (ARRAY['draft'::text,'issued'::text,'paid'::text,'cancelled'::text,'void'::text])));
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_requests_check CHECK ((end_date >= start_date));
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_requests_leave_type_check CHECK ((leave_type = ANY (ARRAY['annual'::text,'sick'::text,'unpaid'::text,'maternity'::text,'paternity'::text,'emergency'::text])));
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text,'approved'::text,'rejected'::text,'cancelled'::text])));
ALTER TABLE public.likes ADD CONSTRAINT likes_target_type_check CHECK ((target_type = ANY (ARRAY['restaurant'::text,'review'::text,'dish'::text])));
ALTER TABLE public.loyalty_accounts ADD CONSTRAINT loyalty_accounts_points_check CHECK ((points >= 0));
ALTER TABLE public.loyalty_accounts ADD CONSTRAINT loyalty_accounts_tier_check CHECK ((tier = ANY (ARRAY['bronze'::text,'silver'::text,'gold'::text,'platinum'::text])));
ALTER TABLE public.operating_hours ADD CONSTRAINT operating_hours_check CHECK ((close_time > open_time));
ALTER TABLE public.operating_hours ADD CONSTRAINT operating_hours_day_of_week_check CHECK (((day_of_week >= 0) AND (day_of_week <= 6)));
ALTER TABLE public.order_items ADD CONSTRAINT order_items_quantity_check CHECK ((quantity > 0));
ALTER TABLE public.order_items ADD CONSTRAINT order_items_status_check CHECK ((status = ANY (ARRAY['pending'::text,'sent_to_kitchen'::text,'preparing'::text,'ready'::text,'served'::text,'cancelled'::text])));
ALTER TABLE public.order_items ADD CONSTRAINT order_items_unit_price_check CHECK ((unit_price >= (0)::numeric));
ALTER TABLE public.orders ADD CONSTRAINT orders_round_check CHECK ((round > 0));
ALTER TABLE public.payment_splits ADD CONSTRAINT payment_splits_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE public.payments ADD CONSTRAINT payments_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE public.payments ADD CONSTRAINT payments_tip_amount_check CHECK ((tip_amount >= (0)::numeric));
ALTER TABLE public.payroll_runs ADD CONSTRAINT payroll_runs_check CHECK ((period_end > period_start));
ALTER TABLE public.payroll_runs ADD CONSTRAINT payroll_runs_status_check CHECK ((status = ANY (ARRAY['draft'::text,'approved'::text,'paid'::text,'cancelled'::text])));
ALTER TABLE public.performance_reviews ADD CONSTRAINT performance_reviews_rating_check CHECK (((rating >= 1) AND (rating <= 5)));
ALTER TABLE public.po_items ADD CONSTRAINT po_items_ordered_qty_check CHECK ((ordered_qty > (0)::numeric));
ALTER TABLE public.po_items ADD CONSTRAINT po_items_received_qty_check CHECK ((received_qty >= (0)::numeric));
ALTER TABLE public.po_items ADD CONSTRAINT po_items_unit_price_check CHECK ((unit_price > (0)::numeric));
ALTER TABLE public.refunds ADD CONSTRAINT refunds_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE public.refunds ADD CONSTRAINT refunds_refund_type_check CHECK ((refund_type = ANY (ARRAY['full'::text,'partial'::text,'goodwill'::text])));
ALTER TABLE public.refunds ADD CONSTRAINT refunds_status_check CHECK ((status = ANY (ARRAY['pending'::text,'processed'::text,'failed'::text])));
ALTER TABLE public.restaurant_settings ADD CONSTRAINT restaurant_settings_booking_slot_minutes_check CHECK ((booking_slot_minutes > 0));
ALTER TABLE public.restaurant_settings ADD CONSTRAINT restaurant_settings_service_charge_check CHECK ((service_charge >= (0)::numeric));
ALTER TABLE public.restaurant_settings ADD CONSTRAINT restaurant_settings_tax_rate_check CHECK ((tax_rate >= (0)::numeric));
ALTER TABLE public.restaurant_subscriptions ADD CONSTRAINT restaurant_subscriptions_status_check CHECK ((status = ANY (ARRAY['trial'::text,'active'::text,'past_due'::text,'cancelled'::text])));
ALTER TABLE public.restaurants ADD CONSTRAINT restaurants_name_check CHECK ((char_length(name) >= 2));
ALTER TABLE public.restaurants ADD CONSTRAINT restaurants_seating_capacity_check CHECK ((seating_capacity > 0));
ALTER TABLE public.restaurants ADD CONSTRAINT restaurants_slug_check CHECK ((slug ~ '^[a-z0-9-]+$'::text));
ALTER TABLE public.restaurants ADD CONSTRAINT restaurants_status_check CHECK ((status = ANY (ARRAY['active'::text,'inactive'::text,'suspended'::text,'pending_approval'::text])));
ALTER TABLE public.review_comments ADD CONSTRAINT review_comments_has_content CHECK (((body IS NOT NULL) OR (photo IS NOT NULL)));
ALTER TABLE public.reviews ADD CONSTRAINT reviews_body_check CHECK ((char_length(body) <= 1000));
ALTER TABLE public.reviews ADD CONSTRAINT reviews_rating_check CHECK (((rating >= 1) AND (rating <= 5)));
ALTER TABLE public.sections ADD CONSTRAINT sections_capacity_check CHECK ((capacity > 0));
ALTER TABLE public.shifts ADD CONSTRAINT shifts_check CHECK ((scheduled_end > scheduled_start));
ALTER TABLE public.stock_alerts ADD CONSTRAINT stock_alerts_alert_type_check CHECK ((alert_type = ANY (ARRAY['low_stock'::text,'out_of_stock'::text,'expiring_soon'::text,'expired'::text])));
ALTER TABLE public.supplier_catalog ADD CONSTRAINT supplier_catalog_unit_price_check CHECK ((unit_price > (0)::numeric));
ALTER TABLE public.supplier_reviews ADD CONSTRAINT supplier_reviews_quality_rating_check CHECK (((quality_rating >= 1) AND (quality_rating <= 5)));
ALTER TABLE public.supplier_reviews ADD CONSTRAINT supplier_reviews_timeliness_rating_check CHECK (((timeliness_rating >= 1) AND (timeliness_rating <= 5)));
ALTER TABLE public.suppliers ADD CONSTRAINT suppliers_payment_terms_check CHECK ((payment_terms = ANY (ARRAY['immediate'::text,'net_7'::text,'net_14'::text,'net_30'::text,'net_60'::text])));
ALTER TABLE public.suppliers ADD CONSTRAINT suppliers_rating_check CHECK (((rating >= (1)::numeric) AND (rating <= (5)::numeric)));
ALTER TABLE public.tables ADD CONSTRAINT tables_capacity_check CHECK ((capacity > 0));
ALTER TABLE public.tables ADD CONSTRAINT tables_check CHECK ((min_capacity <= capacity));
ALTER TABLE public.tables ADD CONSTRAINT tables_min_capacity_check CHECK ((min_capacity > 0));
ALTER TABLE public.tables ADD CONSTRAINT tables_shape_check CHECK ((shape = ANY (ARRAY['square'::text,'round'::text,'rect'::text])));
ALTER TABLE public.tip_distribution ADD CONSTRAINT tip_distribution_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE public.users ADD CONSTRAINT users_age_check CHECK (((age >= 13) AND (age <= 120)));
ALTER TABLE public.users ADD CONSTRAINT users_email_check CHECK ((email ~* '^[^@]+@[^@]+\.[^@]+$'::text));
ALTER TABLE public.users ADD CONSTRAINT users_name_check CHECK ((char_length(name) >= 2));
ALTER TABLE public.users ADD CONSTRAINT users_phone_check CHECK ((phone ~ '^\+?[0-9]{7,15}$'::text));
ALTER TABLE public.waitlist ADD CONSTRAINT waitlist_party_size_check CHECK ((party_size > 0));
ALTER TABLE public.waitlist ADD CONSTRAINT waitlist_status_check CHECK ((status = ANY (ARRAY['waiting'::text,'notified'::text,'booked'::text,'expired'::text,'cancelled'::text])));
ALTER TABLE public.waste_log ADD CONSTRAINT waste_log_quantity_check CHECK ((quantity > (0)::numeric));
ALTER TABLE public.waste_log ADD CONSTRAINT waste_log_waste_type_check CHECK ((waste_type = ANY (ARRAY['spoilage'::text,'prep_trim'::text,'overcooking'::text,'dropped'::text,'expired'::text,'theft'::text,'quality_reject'::text])));

-- 5d. Foreign keys
ALTER TABLE public.ad_campaigns ADD CONSTRAINT ad_campaigns_dish_id_fkey FOREIGN KEY (dish_id) REFERENCES dishes(id) ON DELETE SET NULL;
ALTER TABLE public.ad_campaigns ADD CONSTRAINT ad_campaigns_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
ALTER TABLE public.attendance ADD CONSTRAINT attendance_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES users(id);
ALTER TABLE public.attendance ADD CONSTRAINT attendance_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE public.attendance ADD CONSTRAINT attendance_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES shifts(id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_table_id_fkey FOREIGN KEY (table_id) REFERENCES tables(id);
ALTER TABLE public.bookings ADD CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.customer_profiles ADD CONSTRAINT customer_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.deliveries ADD CONSTRAINT deliveries_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id);
ALTER TABLE public.deliveries ADD CONSTRAINT deliveries_received_by_fkey FOREIGN KEY (received_by) REFERENCES users(id);
ALTER TABLE public.deliveries ADD CONSTRAINT deliveries_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
ALTER TABLE public.delivery_items ADD CONSTRAINT delivery_items_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES deliveries(id) ON DELETE CASCADE;
ALTER TABLE public.delivery_items ADD CONSTRAINT delivery_items_po_item_id_fkey FOREIGN KEY (po_item_id) REFERENCES po_items(id);
ALTER TABLE public.departments ADD CONSTRAINT departments_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
ALTER TABLE public.dish_allergens ADD CONSTRAINT dish_allergens_dish_id_fkey FOREIGN KEY (dish_id) REFERENCES dishes(id) ON DELETE CASCADE;
ALTER TABLE public.dish_allergens ADD CONSTRAINT dish_allergens_from_ingredient_fkey FOREIGN KEY (from_ingredient) REFERENCES ingredients(id);
ALTER TABLE public.dish_ingredients ADD CONSTRAINT dish_ingredients_dish_id_fkey FOREIGN KEY (dish_id) REFERENCES dishes(id) ON DELETE CASCADE;
ALTER TABLE public.dish_ingredients ADD CONSTRAINT dish_ingredients_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES ingredients(id);
ALTER TABLE public.dish_photos ADD CONSTRAINT dish_photos_dish_id_fkey FOREIGN KEY (dish_id) REFERENCES dishes(id) ON DELETE CASCADE;
ALTER TABLE public.dish_photos ADD CONSTRAINT dish_photos_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users(id);
ALTER TABLE public.dish_price_history ADD CONSTRAINT dish_price_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES users(id);
ALTER TABLE public.dish_price_history ADD CONSTRAINT dish_price_history_dish_id_fkey FOREIGN KEY (dish_id) REFERENCES dishes(id);
ALTER TABLE public.dishes ADD CONSTRAINT dishes_menu_section_id_fkey FOREIGN KEY (menu_section_id) REFERENCES menu_sections(id);
ALTER TABLE public.dishes ADD CONSTRAINT dishes_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
ALTER TABLE public.employees ADD CONSTRAINT employees_department_id_fkey FOREIGN KEY (department_id) REFERENCES departments(id);
ALTER TABLE public.employees ADD CONSTRAINT employees_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
ALTER TABLE public.employees ADD CONSTRAINT employees_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES staff(id);
ALTER TABLE public.employees ADD CONSTRAINT employees_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.expenses ADD CONSTRAINT expenses_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES users(id);
ALTER TABLE public.expenses ADD CONSTRAINT expenses_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id);
ALTER TABLE public.expenses ADD CONSTRAINT expenses_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES users(id);
ALTER TABLE public.expenses ADD CONSTRAINT expenses_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
ALTER TABLE public.feedback ADD CONSTRAINT feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE public.ingredient_batches ADD CONSTRAINT ingredient_batches_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES deliveries(id);
ALTER TABLE public.ingredient_batches ADD CONSTRAINT ingredient_batches_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) ON DELETE CASCADE;
ALTER TABLE public.ingredients ADD CONSTRAINT ingredients_preferred_supplier_id_fkey FOREIGN KEY (preferred_supplier_id) REFERENCES suppliers(id);
ALTER TABLE public.ingredients ADD CONSTRAINT ingredients_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id);
ALTER TABLE public.invoices ADD CONSTRAINT invoices_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
ALTER TABLE public.kds_tickets ADD CONSTRAINT kds_tickets_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE;
ALTER TABLE public.kds_tickets ADD CONSTRAINT kds_tickets_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES users(id);
ALTER TABLE public.likes ADD CONSTRAINT likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.loyalty_accounts ADD CONSTRAINT loyalty_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.loyalty_transactions ADD CONSTRAINT loyalty_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.menu_sections ADD CONSTRAINT menu_sections_menu_id_fkey FOREIGN KEY (menu_id) REFERENCES menus(id) ON DELETE CASCADE;
ALTER TABLE public.menus ADD CONSTRAINT menus_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.operating_hours ADD CONSTRAINT operating_hours_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
ALTER TABLE public.order_items ADD CONSTRAINT order_items_dish_id_fkey FOREIGN KEY (dish_id) REFERENCES dishes(id);
ALTER TABLE public.order_items ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;
ALTER TABLE public.orders ADD CONSTRAINT orders_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES bookings(id);
ALTER TABLE public.orders ADD CONSTRAINT orders_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
ALTER TABLE public.orders ADD CONSTRAINT orders_table_id_fkey FOREIGN KEY (table_id) REFERENCES tables(id);
ALTER TABLE public.orders ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.payment_splits ADD CONSTRAINT payment_splits_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id);
ALTER TABLE public.payment_splits ADD CONSTRAINT payment_splits_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payments(id);
ALTER TABLE public.payment_splits ADD CONSTRAINT payment_splits_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.payments ADD CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id);
ALTER TABLE public.payments ADD CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.payroll_items ADD CONSTRAINT payroll_items_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE public.payroll_items ADD CONSTRAINT payroll_items_payroll_run_id_fkey FOREIGN KEY (payroll_run_id) REFERENCES payroll_runs(id) ON DELETE CASCADE;
ALTER TABLE public.payroll_runs ADD CONSTRAINT payroll_runs_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES users(id);
ALTER TABLE public.payroll_runs ADD CONSTRAINT payroll_runs_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
ALTER TABLE public.performance_reviews ADD CONSTRAINT performance_reviews_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE public.performance_reviews ADD CONSTRAINT performance_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES users(id);
ALTER TABLE public.po_items ADD CONSTRAINT po_items_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE;
ALTER TABLE public.po_items ADD CONSTRAINT po_items_supplier_catalog_id_fkey FOREIGN KEY (supplier_catalog_id) REFERENCES supplier_catalog(id);
ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id);
ALTER TABLE public.recipe_versions ADD CONSTRAINT recipe_versions_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES users(id);
ALTER TABLE public.recipe_versions ADD CONSTRAINT recipe_versions_dish_id_fkey FOREIGN KEY (dish_id) REFERENCES dishes(id);
ALTER TABLE public.refunds ADD CONSTRAINT refunds_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES users(id);
ALTER TABLE public.refunds ADD CONSTRAINT refunds_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id);
ALTER TABLE public.refunds ADD CONSTRAINT refunds_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payments(id);
ALTER TABLE public.restaurant_settings ADD CONSTRAINT restaurant_settings_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
ALTER TABLE public.restaurant_subscriptions ADD CONSTRAINT restaurant_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES subscription_plans(id);
ALTER TABLE public.restaurant_subscriptions ADD CONSTRAINT restaurant_subscriptions_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
ALTER TABLE public.restaurant_suppliers ADD CONSTRAINT restaurant_suppliers_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
ALTER TABLE public.restaurant_suppliers ADD CONSTRAINT restaurant_suppliers_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id);
ALTER TABLE public.restaurants ADD CONSTRAINT restaurants_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users(id);
ALTER TABLE public.review_comments ADD CONSTRAINT review_comments_review_id_fkey FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE;
ALTER TABLE public.review_comments ADD CONSTRAINT review_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.reviews ADD CONSTRAINT reviews_dish_id_fkey FOREIGN KEY (dish_id) REFERENCES dishes(id) ON DELETE CASCADE;
ALTER TABLE public.reviews ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.salary_history ADD CONSTRAINT salary_history_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES users(id);
ALTER TABLE public.salary_history ADD CONSTRAINT salary_history_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE public.saved_dishes ADD CONSTRAINT saved_dishes_dish_id_fkey FOREIGN KEY (dish_id) REFERENCES dishes(id) ON DELETE CASCADE;
ALTER TABLE public.saved_dishes ADD CONSTRAINT saved_dishes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.sections ADD CONSTRAINT sections_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
ALTER TABLE public.shifts ADD CONSTRAINT shifts_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE public.shifts ADD CONSTRAINT shifts_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE public.shifts ADD CONSTRAINT shifts_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
ALTER TABLE public.shifts ADD CONSTRAINT shifts_section_id_fkey FOREIGN KEY (section_id) REFERENCES sections(id);
ALTER TABLE public.special_closures ADD CONSTRAINT special_closures_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
ALTER TABLE public.staff ADD CONSTRAINT staff_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
ALTER TABLE public.staff ADD CONSTRAINT staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.stock_alerts ADD CONSTRAINT stock_alerts_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES ingredients(id);
ALTER TABLE public.stock_alerts ADD CONSTRAINT stock_alerts_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
ALTER TABLE public.stock_log ADD CONSTRAINT stock_log_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES ingredient_batches(id);
ALTER TABLE public.stock_log ADD CONSTRAINT stock_log_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES users(id);
ALTER TABLE public.stock_log ADD CONSTRAINT stock_log_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES deliveries(id);
ALTER TABLE public.stock_log ADD CONSTRAINT stock_log_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES ingredients(id);
ALTER TABLE public.supplier_catalog ADD CONSTRAINT supplier_catalog_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE;
ALTER TABLE public.supplier_price_history ADD CONSTRAINT supplier_price_history_supplier_catalog_id_fkey FOREIGN KEY (supplier_catalog_id) REFERENCES supplier_catalog(id);
ALTER TABLE public.supplier_reviews ADD CONSTRAINT supplier_reviews_delivery_id_fkey FOREIGN KEY (delivery_id) REFERENCES deliveries(id);
ALTER TABLE public.supplier_reviews ADD CONSTRAINT supplier_reviews_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
ALTER TABLE public.supplier_reviews ADD CONSTRAINT supplier_reviews_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES users(id);
ALTER TABLE public.supplier_reviews ADD CONSTRAINT supplier_reviews_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id);
ALTER TABLE public.table_state_log ADD CONSTRAINT table_state_log_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES users(id);
ALTER TABLE public.table_state_log ADD CONSTRAINT table_state_log_table_id_fkey FOREIGN KEY (table_id) REFERENCES tables(id);
ALTER TABLE public.tables ADD CONSTRAINT tables_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
ALTER TABLE public.tables ADD CONSTRAINT tables_section_id_fkey FOREIGN KEY (section_id) REFERENCES sections(id);
ALTER TABLE public.tip_distribution ADD CONSTRAINT tip_distribution_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE public.tip_distribution ADD CONSTRAINT tip_distribution_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payments(id);
ALTER TABLE public.user_follows ADD CONSTRAINT user_follows_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;
ALTER TABLE public.user_follows ADD CONSTRAINT user_follows_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_sessions ADD CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE public.waitlist ADD CONSTRAINT waitlist_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);
ALTER TABLE public.waitlist ADD CONSTRAINT waitlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE public.waste_log ADD CONSTRAINT waste_log_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES ingredient_batches(id);
ALTER TABLE public.waste_log ADD CONSTRAINT waste_log_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES ingredients(id);
ALTER TABLE public.waste_log ADD CONSTRAINT waste_log_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES users(id);
ALTER TABLE public.waste_log ADD CONSTRAINT waste_log_restaurant_id_fkey FOREIGN KEY (restaurant_id) REFERENCES restaurants(id);

-- 5e. Exclusion constraints (need btree_gist)
ALTER TABLE public.bookings ADD CONSTRAINT bookings_table_id_tstzrange_excl EXCLUDE USING gist (table_id WITH =, tstzrange(reserved_from, reserved_until, '[)'::text) WITH &&) WHERE ((status <> 'cancelled'::booking_status));
ALTER TABLE public.shifts ADD CONSTRAINT shifts_employee_id_tstzrange_excl EXCLUDE USING gist (employee_id WITH =, tstzrange(scheduled_start, scheduled_end) WITH &&);

-- NOTE: Functions, indexes, views, matviews, triggers, RLS+policies, realtime,
-- and grants are in _prod_baseline_part3.sql — run it AFTER this file.
